### ISSUE TITLE
Add internal "admin" loadbalancer

### ISSUE THREAD

**Issue by corang** [defenseunicorns/zarf-package-software-factory#605]
Add a second istio ingressgateway that's meant for administrative services that don't need to be exposed to the public.

Example istio config from @ntwkninja 
```
istio:
  enabled: true
  # null out the ingress to prevent the common `afwerx.dso.mil` key/cert from being used
  ingress: null
  ingressGateways:
    public:
      type: LoadBalancer
      kubernetesResourceSpec:
        serviceAnnotations:
          # Enable cross zone load balancing
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
        hpaSpec:
          minReplicas: 3
          maxReplicas: 5
    private:
      type: LoadBalancer
      kubernetesResourceSpec:
        serviceAnnotations:
          # Ensure mission apps have internal load balancer only
          service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
          # Enable cross zone load balancing
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
  values:
    istiod:
      hpaSpec:
        minReplicas: 3
        maxReplicas: 5
    values:
      global:
        proxy:
          resources:
            limits:
              memory: 512Mi
              cpu: 400m
            requests:
              memory: 64Mi
              cpu: 50m
  gateways:
    private:
      ingressGateway: private
      hosts:
        - gitlab-registry.{{ .Values.domain }}
        - tracing.{{ .Values.domain }}
        - kiali.{{ .Values.domain }}
        - kibana.{{ .Values.domain }}
        - alertmanager.{{ .Values.domain }}
        - prometheus.{{ .Values.domain }}
        - twistlock.{{ .Values.domain }}
        - loki.{{ .Values.domain }}
        - rapidfort.{{ .Values.domain }}
      tls:
        no: hi
    public:
      ingressGateway: public
      hosts:
        - code.{{ .Values.domain }}
        - nexus.{{ .Values.domain }}
        - grafana.{{ .Values.domain }}
        - registry.{{ .Values.domain }}
        - registry-unapproved.{{ .Values.domain }}
        - registry-approved.{{ .Values.domain }}
        - registry-external.{{ .Values.domain }}
      tls:
        no: hi
```
