### ISSUE TITLE
Gitlab Runner package

### ISSUE THREAD

**Issue by JaseKoonce** [defenseunicorns/zarf-package-software-factory#618]
Is it possible to create and continue and support a Zarf Gitlab Runner package. This is what we are currently using for reference: 

Zarf.yaml : 
 ```yaml
    kind: ZarfPackageConfig
    metadata:
      name: gitlab-runner
      description: "Deploy Gitlab-runner"
    
    components:
      - name: gitlab-runner
        required: true
        charts:
          - name: gitlab-runner
            url: https://repo1.dso.mil/big-bang/product/packages/gitlab-runner.git
            gitPath: chart
            namespace: gitlab
            version: "###ZARF_PKG_VAR_GITLAB_RUNNER_TAG###"
            valuesFiles:
              - values.yaml
        images:
          - registry1.dso.mil/ironbank/gitlab/gitlab-runner/gitlab-runner:v15.0.0
          - registry1.dso.mil/ironbank/gitlab/gitlab-runner/gitlab-runner-helper:v15.0.0
          - registry1.dso.mil/ironbank/redhat/ubi/ubi8:8.6 
 ```

values.yaml: 
 ```yaml
gitlabUrl: GITLAB_URL
    runnerRegistrationToken:

    runners:
      config: |
        [[runners]]
          clone_url = "GITLAB_URL"
          cache_dir = "/tmp/gitlab-runner/cache"
          privileged = true
          [runners.kubernetes]
            namespace = "{{.Release.Namespace}}"
            image = "registry1.dso.mil/ironbank/redhat/ubi/ubi8:8.6"
            helper_image = "registry1.dso.mil/ironbank/gitlab/gitlab-runner/gitlab-runner-helper:v15.0.0"
            image_pull_secrets = ["private-registry"]
          [runners.kubernetes.pod_labels]
            "job_id" = "${CI_JOB_ID}"
            "job_name" = "${CI_JOB_NAME}"
            "pipeline_id" = "${CI_PIPELINE_ID}"
 ```                       

Makefile:
```
# The version of Zarf to use. To keep this repo as portable as possible the Zarf binary will be downloaded and added to
# the build folder.
ZARF_VERSION := v0.25.1

# Figure out which Zarf binary we should use based on the operating system we are on
ZARF_BIN := zarf

.DEFAULT_GOAL := help

# Provide a value for the operating system architecture and processor to install the correct terraform binary
ifeq ($(OS),Windows_NT)
	ARCH_NAME := windows
	ARCH_PROC := amd64
else
	UNAME_S := $(shell uname -s)
	UNAME_P := $(shell uname -p)
	ifeq ($(UNAME_S),Darwin)
		ARCH_NAME := darwin
		ARCH_PROC := amd64
		ifeq ($(UNAME_P),arm)
			ARCH_PROC := arm64
		endif
	endif
	ifeq ($(UNAME_S),Linux)
		ARCH_NAME := linux
		ifeq ($(UNAME_P),amd)
			ARCH_PROC := amd64
		endif
		ifeq ($(UNAME_P),i386)
			ARCH_PROC := 386
		endif
		ifeq ($(UNAME_P),arm)
			ARCH_PROC := arm64
		endif
	endif
endif

# Set gitlab-runner version
GITLAB_RUNNER_TAG := 0.41.0-bb.0

# Idiomatic way to force a target to always run, by having it depend on this dummy target
FORCE:

.PHONY: help
help: ## Show a list of all targets
	@grep -E '^\S*:.*##.*$$' $(MAKEFILE_LIST) \
	| sed -n 's/^\(.*\): \(.*\)##\(.*\)/\1:\3/p' \
	| column -t -s ":"

.PHONY: clean
clean: ## Clean up build files
	@rm -rf ./build

mkdir: 
	@mkdir -p build

.PHONY: build
build: mkdir ## Build the IaC Zarf Package
	@echo "Creating the deploy package"
	@$(ZARF_BIN) package create --set GITLAB_RUNNER_TAG=$(GITLAB_RUNNER_TAG) --confirm
	@mv zarf-package-gitlab-runner-$(ARCH_PROC).tar.zst build/zarf-package-gitlab-runner-$(GITLAB_RUNNER_TAG)-$(ARCH_PROC).tar.zst
```

### Context:
It was decided that we should create this issue with zarf-package-software-factory (DI2ME) as this gitlab-runner pkg should stay in sync with DI2ME. This could also be beneficial to other DI2ME users.
